name: Backend CI

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        working-directory: backend
        run: |
          echo "${{ secrets.ENV_PROD }}" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/1-load-test-be-user:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/1-load-test-be-user:latest